# Generated by Django 5.2.7 on 2025-12-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='message',
        #    name='image',
        #    field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        #),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
