# Generated by Django 5.2.7 on 2025-10-17 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('banner_pic', models.ImageField(blank=True, null=True, upload_to='itinerary_banners/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TouristicPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_api_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('external_api_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('opening_hours', models.TextField(blank=True)),
                ('categories', models.ManyToManyField(related_name='places', to='itineraries.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('touristic_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.touristicplace')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('placement', models.PositiveSmallIntegerField()),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itinerary')),
                ('touristic_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.touristicplace')),
            ],
            options={
                'ordering': ['day_number', 'placement'],
                'unique_together': {('itinerary', 'day_number', 'placement')},
            },
        ),
    ]
