# Generated by Django 5.2.7 on 2025-11-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_itinerarystop_lat_itinerarystop_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystop',
            name='photo',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la parada en el itinerario.', null=True, upload_to='itinerary_stop_photos/'),
        ),
    ]
