# Generated by Django 5.2.7 on 2025-11-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_itinerarystop_lat_itinerarystop_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystop',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itinerarystop',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
