# Generated by Django 5.2.7 on 2025-11-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_itinerarystop_lat_itinerarystop_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristicplace',
            name='photo',
        ),
    ]
