# Generated by Django 5.2.7 on 2025-11-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_remove_touristicplace_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristicplace',
            name='photo',
            field=models.ImageField(blank=True, help_text='Imagen representativa del lugar turístico.', null=True, upload_to='place_photos/'),
        ),
    ]
