# Generated by Django 5.2.7 on 2025-11-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_touristicplace_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarystop',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='itinerarystop',
            name='long',
        ),
        migrations.RemoveField(
            model_name='itinerarystop',
            name='photo',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10),
        ),
    ]
