# Generated by Django 5.2.7 on 2025-11-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_remove_itinerarystop_lat_remove_itinerarystop_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='location',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
