# Generated by Django 5.2.7 on 2025-11-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_remove_itinerarystop_lat_remove_itinerarystop_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='location',
        ),
    ]
