# Generated by Django 5.2.7 on 2025-11-26 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0010_itinerary_likes_itinerary_saved_by_itinerarycomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarycomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='itineraries.itinerarycomment'),
        ),
    ]
