# Generated by Django 5.2.7 on 2025-12-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0011_itinerarycomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='privacy',
            field=models.CharField(choices=[('public', 'Público'), ('friends', 'Solo Amigos'), ('private', 'Solo Yo')], default='public', max_length=10),
        ),
    ]
