# Generated by Django 5.2.7 on 2025-11-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0009_remove_itinerary_location'),
        ('itineraries', '0011_itinerarycomment_parent'),
    ]

    operations = [
    ]
