# Generated by Django 5.2.7 on 2025-12-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0012_itinerary_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristicplace',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
