# Generated by Django 5.2.7 on 2025-12-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0012_itinerary_privacy'),
        ('itineraries', '0013_touristicplace_is_active'),
    ]

    operations = [
    ]
