# Generated by Django 5.2.7 on 2025-12-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0015_merge_20251210_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Define si el itinerario es visible en la plataforma. Usado para moderación.'),
        ),
    ]
