# Generated by Django 5.2.7 on 2025-12-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0013_touristicplace_is_active'),
        ('itineraries', '0016_itinerary_is_active'),
    ]

    operations = [
    ]
