# Generated by Django 5.2.7 on 2025-10-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='itineraries.category'),
        ),
    ]
