# Generated by Django 5.2.7 on 2025-12-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginlog'),
        ('users', '0002_profile_preferred_categories'),
    ]

    operations = [
    ]
