# Generated by Django 5.2.7 on 2025-10-22 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='content_type_model',
        ),
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.TextField(default='', help_text='Motivo del reporte.'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('REVIEWED', 'Revisado'), ('DISMISSED', 'Desestimado')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='reports_rep_content_7967a9_idx'),
        ),
    ]
