# Generated by Django 5.2.7 on 2025-11-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_likes_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Público'), ('friends', 'Solo Amigos')], default='public', help_text='Define quién puede ver esta publicación', max_length=10),
        ),
    ]
