# Generated by Django 5.2.7 on 2025-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_itinerary_alter_comment_post_itineraryrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desactívalo para ocultar el post (Moderación)'),
        ),
    ]
