# Generated by Django 5.2.7 on 2025-12-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Público'), ('friends', 'Solo Amigos'), ('private', 'Solo Yo')], default='public', help_text='Define quién puede ver esta publicación', max_length=10),
        ),
    ]
